services:
  proxy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mailhog
      - postfix
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/camac/nginx:/etc/nginx/conf.d:ro

  django: &django
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      cache_from:
        - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    depends_on:
      - postfix
      - mailhog
    environment:
      - DATABASE_HOST=${SZ_DATABASE_HOST_STAGE}
      - DJANGO_ENV_FILE=/run/secrets/django.env
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro
      - /etc/camac/django/uwsgi-prod.ini:/app/uwsgi.ini
    restart: always

  django-q:
    <<: *django
    environment:
      - DJANGO_ENV_FILE=/run/secrets/django.env
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro
    command: /bin/sh -c "./wait-for-it.sh $SZ_DATABASE_HOST_STAGE:5431 -- ./manage.py qcluster --pythonpath /app/$APPLICATION"

  ember:
    image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        KEYCLOAK_URL_ARG: ${KEYCLOAK_URL}
        INTERNAL_HOST_ARG: ${INTERNAL_HOST}
        DEPLOY_TARGET: staging
    restart: always

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always

  cache:
    restart: always

  unoconv:
    restart: always

  clamav:
    restart: always

  keycloak:
    volumes:
      - /etc/camac/keycloak.env:/run/secrets/keycloak.env:ro
    environment:
      - ENV_FILE=/run/secrets/keycloak.env
    restart: always

  postfix:
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=camac-schwyz.sycloud.ch
      - POSTFIX_mail_name=noreply@camac-schwyz.sycloud.ch

  mailhog:
    image: mailhog/mailhog
    restart: always
    environment:
      - MH_UI_WEB_PATH=mailhog
      - MH_AUTH_FILE=/run/secrets/mailhog_auth
    volumes:
      - /etc/camac/mailhog_auth:/run/secrets/mailhog_auth:ro

  metabase:
    environment:
      - MB_DB_USER=${METABASE_DB_USER_STAGE}
      - MB_DB_PASS=${METABASE_DB_PASS_STAGE}
      - MB_DB_HOST=${SZ_DATABASE_HOST_STAGE}
    restart: always

volumes:
  djangomedia:
    external:
      name: camacdjangomedia

  phpsessions:
    external:
      name: camacphpsessions
